#!/bin/bash

# This test file will be executed against after building a container with the
# 'ubuntu_24_custom_version' scenario in 'test/test/zivid/scenarios.json'.
#
# This scenario tests the Zivid feature with Ubuntu 24.04 and custom Zivid version.
#
# This test (as well as any of the other scenarios in 'scenarios.json') can be run with the following command:
#
#    devcontainer features test \
#               --features zivid \
#               --skip-autogenerated \
#               /path/to/this/repo

set -e

# Optional: Import test library bundled with the devcontainer CLI
# Provides the 'check' and 'reportResults' commands.
source dev-container-features-test-lib

echo "Running Zivid Ubuntu 24.04 custom version tests..."

# Feature-specific tests
# Test that Zivid is properly installed with custom version settings
check "zivid package installed" dpkg -l | grep -i zivid
check "video group exists" getent group video
check "render group exists" getent group render
check "zivid-studio command exists" which ZividStudio
check "zivid-list-cameras command exists" which ZividListCameras
check "OpenCL vendor config exists" test -f /etc/OpenCL/vendors/nvidia.icd

# Report result
reportResults